language: ruby

sudo: false

cache: bundler

before_install:
  - gem uninstall bundler -aIxq --force
  - gem uninstall -Ixq --force -i /home/travis/.rvm/gems/ruby-2.2.3@global bundler
  - gem install bundler -v '1.12.5'

addons:
  apt:
    packages:
    - bsdtar

rvm:
  - 2.2.3

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: bundle exec rake test:unit
